platform :ios, '9.0'

target 'Example' do

  pod 'ExtJSBridge', :path=>'../'
  
  pod 'AFNetworking'
  
  target 'ExampleTests' do
    inherit! :search_paths
  end

  target 'ExampleUITests' do
    inherit! :search_paths
  end

end
